VN-524 add hanlding for network interuption cases
anyTV/electron-dl pull request #2
Opened 2018-11-23 06:04 UTC by huy2nhan

There're 2 cases covered on this change:
1. Network is interupted before the invoke of  `webContents.downloadURL()`, downloadItem does not raise `close` event but `updated` event with `state=interupted`. 
 - Current behavior: it hangs there forever event the network is back
 - Solution: we add retry for 3 times before force closing the download ourself.

2. The download is in progress and got network interuption.
 - Current behavior:
    - If network is back: the download is resume and can finish it
    - if the network is never back, it hangs there forever
 - Solution: we add a tracking of unchanged progress for awhile and force to close the downlaod ourself.

2018-11-23 06:05 UTC, huy2nhan commented
@anyTV/freedom-vn-team please review

2018-11-23 07:51 UTC, pandafox requested changes

2018-11-23 07:51 UTC, pandafox commented on index.js
> +        if (handlers.noProgress === 20) {
Move these into a config file or at least constant for clear declaration.

2018-11-23 07:51 UTC, pandafox commented on index.js
> +        reject(new Error(`Failed to start download for ${key}`));
return reject?

2018-11-23 07:51 UTC, pandafox commented on index.js
> +        setTimeout(() => {
return?

2018-11-23 07:51 UTC, pandafox commented on index.js
> +          reject(new Error(`Failed to download for ${key}`));
return?

2018-11-28 07:25 UTC, huy2nhan commented
Updated to your feedback, please review again @pandafox

2018-11-28 09:38 UTC, pandafox requested changes

2018-11-28 09:38 UTC, pandafox commented on index.js
> +					item.resume();
format

2018-11-28 09:38 UTC, pandafox commented on index.js
> +				// Electron does not raised interupted state for this case at the moment, so we handle ourself
format?

2018-11-28 09:38 UTC, pandafox commented on index.js
> +      if (handlers.retryCount === 3) {
Move this limit to config, also use >= to capture the possible case that it may be incremented before you can check it.

2018-11-29 03:17 UTC, angels2it reviewed
Should we format code of electron-dl to our code convension?.
I have a PR to origin electron-dl repo but seems they did not review or maintain it anymore :(

2018-11-29 03:17 UTC, angels2it commented on index.js
> +      if (handlers.retryCount === 3) {
By code of L47, handlers is nullable, so it may caused error here

2018-11-29 04:38 UTC, huy2nhan commented
@anyTV/freedom-vn-team thanks for the feedbacks, please review again

2018-11-29 07:51 UTC, pandafox commented on index.js
> +    session.on('will-download', registerListener(session));
This should be either

```
session.on('will-download', registerListener(session).bind(this))
or
session.on('will-download', () => registerListener(session))
```

2018-12-03 03:46 UTC, pandafox commented on index.js
> +  if (!win.isDestroyed()) {
Should we also check if win exists or not?

2018-12-03 03:46 UTC, pandafox approved these changes

2018-12-03 10:02 UTC, merged